services:
  hotels-db:
    image: postgres:17-alpine

    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: hotels

    volumes:
      - hotels_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking -d hotels"]
      interval: 5s
      timeout: 3s
      retries: 10


  hotels-migrate:
    image: migrate/migrate:latest

    volumes:
      - ./hotelsvc/migrations:/migrations:ro

    command:
      [
        "-path=/migrations",
        "-database=postgres://booking:booking@hotels-db:5432/hotels?sslmode=disable",
        "up"
      ]

    depends_on:
      hotels-db:
        condition: service_healthy


  bookings-db:
    image: postgres:17-alpine

    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: bookings

    volumes:
      - bookings_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking -d bookings"]
      interval: 5s
      timeout: 3s
      retries: 10


  bookings-migrate:
    image: migrate/migrate:latest

    volumes:
      - ./bookingsvc/migrations:/migrations:ro

    command:
      [
        "-path=/migrations",
        "-database=postgres://booking:booking@bookings-db:5432/bookings?sslmode=disable",
        "up"
      ]

    depends_on:
      bookings-db:
        condition: service_healthy


  hotelsvc:
    build:
      context: ./hotelsvc
      dockerfile: Dockerfile

    environment:
      DB_DSN: "postgres://booking:booking@hotels-db:5432/hotels?sslmode=disable"

    depends_on:
      hotels-db:
        condition: service_healthy

      hotels-migrate:
        condition: service_completed_successfully

    ports:
      - "8080:8080"
      - "50051:50051"


  bookingsvc:
    build:
      context: ./bookingsvc
      dockerfile: Dockerfile

    environment:
      POSTGRES_DSN: "postgres://booking:booking@bookings-db:5432/bookings?sslmode=disable"

    depends_on:
      bookings-db:
        condition: service_healthy

      bookings-migrate:
        condition: service_completed_successfully

      hotelsvc:
        condition: service_started

      kafka:
        condition: service_healthy

    ports:
      - "8081:8081"

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: CONTROLLER://:29093,DOCKER://:29092,LOCAL://:9092

      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka:29092,LOCAL://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,LOCAL:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  hotels_data:
  bookings_data:
  kafka-data: