version: "3"

vars:
  BIN_DIR: '{{.ROOT_DIR}}/bin'
  BUF: '{{.BIN_DIR}}/buf'
  BUF_VERSION: '1.53.0'

tasks:
  install-buf:
    desc: "Устанавливает Buf в каталог bin"
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        [ -f {{.BUF}} ] || {
          echo '📦 Устанавливаем buf {{.BUF_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/bufbuild/buf/cmd/buf@v{{.BUF_VERSION}}
        }
    status:
      - test -x {{.BUF}}
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/hotelsvc/rooms/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  proto:update-deps:
    deps: [ install-buf ]
    desc: Обновляет зависимости protobuf из удаленных репозиториев (googleapis и т.д.)
    dir: proto
    cmds:
      - |
        echo "🔄 Обновляем зависимости buf..."
        {{.BUF}} dep update