env: "local"

http:
  host: "localhost"
  port: "8081"
  read_header_timeout: 5s
  read_timeout: 10s
  write_timeout: 15s
  idle_timeout: 60s

clients:
  hotelsvc:
    grpc:
      host: "localhost"
      port: "50051"
      timeout: 5s