env: "local"
database:
  dsn: "user=booking_user password=booking_pass dbname=booking_db sslmode=disable"
grpc:
  port: 50051
  timeout: 10h
http:
  port: 8080
  readHeaderTimeout: 5s
  readTimeout: 10s
  writeTimeout: 15s
  idleTimeout: 60s